USE CreditAdmin
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
--CREATE TABLE [FRB\mlan].[FICO_CLIENT](
--	[PROD_DT] [date] NOT NULL,
--	[DATE_KEY] [int] NOT NULL,
--	[WP_OID] [char](15) NOT NULL,
--	[SUBMISSION_DATE] [date] NOT NULL,
--	[CUSTOMER_XREF_ID] [char](15) NOT NULL,
--	[RELATIVE_CB_NUM] [char](2) NULL,
--	[LAST_NM] [char](30) NULL,
--	[OBLG_NBR] [decimal](10, 0) NULL,
--	[FICO_ORIG] [int] NULL,
--	[SSN] [char](9) NULL,
--	[TIN] [char](10) NULL,
--	[CLIENT NAME] [varchar](255) NULL,
--	[ORIGIN] [VARCHAR](255) NOT NULL,
--	[INSERTDT] [date] NOT NULL
--) ON [PRIMARY]
--GO
DECLARE @DATE_KEY INT = 20180228;
WITH DT AS (
SELECT DISTINCT PROD_DT
FROM [EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST]
WHERE MONTH(PROD_DT) = MONTH(CONVERT(DATE, CONVERT(VARCHAR, @DATE_KEY)))+1 AND YEAR(PROD_DT) = YEAR(CONVERT(DATE, CONVERT(VARCHAR, @DATE_KEY)))
)
DELETE FROM [CreditAdmin].[FRB\mlan].[FICO_CLIENT] WHERE PROD_DT = (SELECT MIN(PROD_DT) FROM DT);
-----=====RUN QUERY BELOW TO GET NEW REPORTING PERIOD ORIGINAL FICO RESULT===============
WITH DT AS (
SELECT DISTINCT PROD_DT
FROM [EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST]
WHERE MONTH(PROD_DT) = MONTH(CONVERT(DATE, CONVERT(VARCHAR, @DATE_KEY)))+1 AND YEAR(PROD_DT) = YEAR(CONVERT(DATE, CONVERT(VARCHAR, @DATE_KEY)))
)
SELECT CAST([EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST].PROD_DT AS DATE) AS PROD_DT, 
       DATE_KEY = @DATE_KEY,
       [EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST].WP_OID, 
       CAST(MAX([EAGLEVISION].[DBO].[V_AFSXFI_CONSMR_ANLY_INFO_HIST].SUBMISSION_DATE) AS DATE) AS 
       MAXOFSUBMISSION_DATE, 
       [EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST].CUSTOMER_XREF_ID, 
       [EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST].RELATIVE_CB_NUM, 
       [EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST].SSN, 
       CAST(LTRIM(RTRIM([EAGLEVISION].[DBO].[V_AFSXFI_CONSMR_ANLY_INFO_HIST].CBA_OL_CB_SCORE1)) AS INT) AS CLIENT_SCORE, 
       [EAGLEVISION].[DBO].[V_AFSX_CUST_BORR_HIST].OBLG_NBR, 
       [EAGLEVISION].[DBO].[V_AFSX_CUST_BORR_HIST].TIN, 
       [EAGLEVISION].[DBO].[V_AFSX_CUST_BORR_HIST].[LAST_NM], 
       LTRIM(RTRIM([EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST].CB_FORMAT_NAME )) AS CB_FORMAT_NAME,
	   '[EAGLEVISION].[DBO].[V_AFSXFI_CONSMR_ANLY_INFO_HIST].[CBA_OL_CB_SCORE1]' AS ORIGINAL_SOURCE,
	   GETDATE() AS INSERT_DATE
INTO #CLIENT_ALL
FROM   ([EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST] 
	INNER JOIN [EAGLEVISION].[DBO].[V_AFSXFI_CONSMR_ANLY_INFO_HIST] 
	ON ( [EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST].WP_OID = [EAGLEVISION].[DBO].[V_AFSXFI_CONSMR_ANLY_INFO_HIST].WP_OID ) 
		AND ( [EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST].CUSTOMER_XREF_ID = [EAGLEVISION].[DBO].[V_AFSXFI_CONSMR_ANLY_INFO_HIST].CUSTOMER_XREF_ID ) 
		AND ( [EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST].PROD_DT = [EAGLEVISION].[DBO].[V_AFSXFI_CONSMR_ANLY_INFO_HIST].PROD_DT )) 
	INNER JOIN [EAGLEVISION].[DBO].[V_AFSX_CUST_BORR_HIST] 
	ON ( [EAGLEVISION].[DBO].[V_AFSXFI_CONSMR_ANLY_INFO_HIST].WP_OID = [EAGLEVISION].[DBO].[V_AFSX_CUST_BORR_HIST].WUM_ID ) 
		AND ( [EAGLEVISION].[DBO].[V_AFSXFI_CONSMR_ANLY_INFO_HIST].PROD_DT = [EAGLEVISION].[DBO].[V_AFSX_CUST_BORR_HIST].PROD_DT ) 
GROUP  BY [EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST].PROD_DT, 
          [EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST].WP_OID, 
          [EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST].CUSTOMER_XREF_ID, 
          [EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST].RELATIVE_CB_NUM, 
          [EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST].SSN, 
          [EAGLEVISION].[DBO].[V_AFSXFI_CONSMR_ANLY_INFO_HIST].CBA_OL_CB_SCORE1, 
          [EAGLEVISION].[DBO].[V_AFSX_CUST_BORR_HIST].OBLG_NBR, 
          [EAGLEVISION].[DBO].[V_AFSX_CUST_BORR_HIST].TIN, 
          [EAGLEVISION].[DBO].[V_AFSX_CUST_BORR_HIST].LAST_NM, 
          [EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST].CB_FORMAT_NAME 
HAVING  ( (( [EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST].PROD_DT ) =  (SELECT MIN(PROD_DT) FROM DT))
--MAX([EAGLEVISION].[DBO].[V_AFSXFI_PRIN_INFO_HIST].PROD_DT) ) --(SELECT DISTINCT PROD_DT FROM SUBMISSION) )--'2018-03-16 00:00:00.000' ) 
         AND (( [EAGLEVISION].[DBO].[V_AFSXFI_CONSMR_ANLY_INFO_HIST].CBA_OL_CB_SCORE1 ) <> 'N' )
         AND (( [EAGLEVISION].[DBO].[V_AFSXFI_CONSMR_ANLY_INFO_HIST].CBA_OL_CB_SCORE1 ) <> 'X') 
         AND (( [EAGLEVISION].[DBO].[V_AFSXFI_CONSMR_ANLY_INFO_HIST].CBA_OL_CB_SCORE1 ) NOT LIKE '*' )
         AND (( [EAGLEVISION].[DBO].[V_AFSX_CUST_BORR_HIST].OBLG_NBR ) > 0)  )
ORDER  BY MAX([EAGLEVISION].[DBO].[V_AFSXFI_CONSMR_ANLY_INFO_HIST].SUBMISSION_DATE) DESC; 
--==--
INSERT INTO [CreditAdmin].[FRB\mlan].[FICO_CLIENT] 
            (PROD_DT, 
			 DATE_KEY,
             WP_OID , 
             SUBMISSION_DATE, 
             CUSTOMER_XREF_ID, 
             RELATIVE_CB_NUM, 
             SSN, 
             FICO_ORIG, 
             [OBLG_NBR], 
             TIN , 
             LAST_NM, 
             [CLIENT NAME],
			 [ORIGIN],
			 [INSERTDT]) 
SELECT 
       PROD_DT, 
       DATE_KEY,
       WP_OID,
       MAXOFSUBMISSION_DATE, 
       CUSTOMER_XREF_ID, 
       RELATIVE_CB_NUM, 
       SSN, 
       CLIENT_SCORE, 
       OBLG_NBR, 
       TIN, 
       [LAST_NM], 
       CB_FORMAT_NAME,
	   ORIGINAL_SOURCE,
	   GETDATE() AS INSERT_DATE
FROM #CLIENT_ALL;
--==--
DROP TABLE #CLIENT_ALL;
--===============================CREATE/APPEND CLIENT SCORE RECORD WITH VALID FICO======================================================
DECLARE @DATE_KEY INT = 20180228;
DELETE FROM [CreditAdmin].[FRB\mlan].[FICO_CLIENT_NONZERO]  WHERE DATE_KEY = @DATE_KEY;
WITH NON_ZERO AS (SELECT * FROM [CreditAdmin].[FRB\mlan].[FICO_CLIENT] WHERE DATE_KEY = @DATE_KEY AND (FICO_ORIG<851 AND FICO_ORIG>299) ) 
INSERT INTO [CreditAdmin].[FRB\mlan].[FICO_CLIENT_NONZERO] 
            (PROD_DT, 
			DATE_KEY,
             WP_OID, SUBMISSION_DATE, 
             CUSTOMER_XREF_ID, RELATIVE_CB_NUM, 
             SSN, 
             FICO_ORIG, [OBLG_NBR], 
             TIN, LAST_NM, 
             [CLIENT NAME],[ORIGIN],
			 [INSERTDT]) 
SELECT       PROD_DT, 
			 DATE_KEY,
             WP_OID , 
             SUBMISSION_DATE, 
             CUSTOMER_XREF_ID, 
             RELATIVE_CB_NUM, 
             SSN, 
             FICO_ORIG, 
             [OBLG_NBR], 
             TIN , 
             LAST_NM, 
             [CLIENT NAME], 
			 [ORIGIN],
			 GETDATE()
FROM NON_ZERO;
--================CREATE VIEW IN CREDITADMIN========================================================================
--alter VIEW [Client FICO SCORES] AS 
--SELECT * FROM [CreditAdmin].[FRB\mlan].[FICO_CLIENT_NONZERO] WHERE DATE_KEY = 20180228
--GO

/**--=================CREATE UNIQUE FICO TO TIN/OBLG TABLE. SO EACH TIN/OBLG WILL HAVE A UNIQUE FICO ASSIGNED===================================================
  WITH TEMP AS ()
  SELECT * FROM TEMP WHERE FICOMIN = 0 

   --SELECT COUNT(DISTINCT [OBLG_NBR]) FROM [CREDITADMIN].[FRB\MLAN].[FICO_CLIENT_NONZERO];

  WITH OBLG_TEMP AS (
  SELECT *, PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY FICO_ORIG ASC) OVER (PARTITION BY [OBLG_NBR]) AS MedianFICO
  FROM [CREDITADMIN].[FRB\MLAN].[FICO_CLIENT_NONZERO]  )  
  SELECT [OBLG_NBR], COUNT([OBLG_NBR]) LOAN#, MedianFICO,-- PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY FICO_ORIG ASC) OVER (PARTITION BY [OBLG_NBR]) AS MedianFICO,
  MIN(FICO_ORIG) FICOMIN, MAX(FICO_ORIG) FICOMAX, AVG(FICO_ORIG) FICOAVG, COUNT( DISTINCT  [FICO_ORIG]) FICO#,
  'OBLG_NBR' AS SOURCE_TYPE, [ORIGIN]
  FROM OBLG_TEMP
  GROUP BY [OBLG_NBR],MedianFICO,ORIGIN

   --SELECT COUNT(DISTINCT SSN) FROM [CREDITADMIN].[FRB\MLAN].[FICO_CLIENT_NONZERO];
  WITH SSN_TEMP AS (
  SELECT *, PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY FICO_ORIG ASC) OVER (PARTITION BY [SSN]) AS MedianFICO
  FROM [CREDITADMIN].[FRB\MLAN].[FICO_CLIENT_NONZERO] WHERE LEN(SSN) >0   )
  SELECT SSN, COUNT(SSN) LOAN#,MedianFICO,-- PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY FICO_ORIG ASC) OVER (PARTITION BY SSN) AS MedianFICO,
  MIN(FICO_ORIG) FICOMIN, MAX(FICO_ORIG) FICOMAX, AVG(FICO_ORIG) FICOAVG, COUNT( DISTINCT  [FICO_ORIG]) FICO#,
  'SSN' AS SOURCE_TYPE, [ORIGIN]
  FROM SSN_TEMP
  GROUP BY SSN,MedianFICO,ORIGIN

   --SELECT COUNT(DISTINCT TIN) FROM [CREDITADMIN].[FRB\MLAN].[FICO_CLIENT_NONZERO];
  WITH TIN_TEMP AS (
  SELECT *, PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY FICO_ORIG ASC) OVER (PARTITION BY [TIN]) AS MedianFICO
  FROM [CREDITADMIN].[FRB\MLAN].[FICO_CLIENT_NONZERO] WHERE LEN(TIN) >0    )
  SELECT TIN, COUNT(TIN) LOAN#,MedianFICO,-- PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY FICO_ORIG ASC) OVER (PARTITION BY TIN) AS MedianFICO,
  MIN(FICO_ORIG) FICOMIN, MAX(FICO_ORIG) FICOMAX, AVG(FICO_ORIG) FICOAVG, COUNT( DISTINCT  [FICO_ORIG]) FICO#,
  'TIN' AS SOURCE_TYPE, [ORIGIN]
  FROM TIN_TEMP
  GROUP BY TIN,MedianFICO,ORIGIN
**/