USE SB_PA_MARGARET
GO

DROP TABLE #ALL; 
DROP TABLE #STATUS;

DECLARE @DATE_KEY INT = 20180228;  -- SET MONTH END DATE

DECLARE @AFS_PROD_DT DATE = CASE
								WHEN DATEPART(DW,CONVERT(DATE, CONVERT(VARCHAR,@DATE_KEY)))=1 THEN DATEADD(DAY, -2, CONVERT(DATE, CONVERT(VARCHAR,@DATE_KEY)))
								WHEN DATEPART(DW,CONVERT(DATE, CONVERT(VARCHAR,@DATE_KEY)))=7 THEN DATEADD(DAY, -1, CONVERT(DATE, CONVERT(VARCHAR,@DATE_KEY)))
								ELSE CONVERT(DATE, CONVERT(VARCHAR,@DATE_KEY))
							END;

DECLARE @OSI_PROD_DT DATE = CASE
								WHEN DATEPART(DW,CONVERT(DATE, CONVERT(VARCHAR,@DATE_KEY)))=1 THEN DATEADD(DAY, -1, CONVERT(DATE, CONVERT(VARCHAR,@DATE_KEY)))
								ELSE CONVERT(DATE, CONVERT(VARCHAR,@DATE_KEY))
							END;

DECLARE @RDM_PROD_DT DATE = CONVERT(DATE, CONVERT(VARCHAR, @DATE_KEY));


DECLARE @LAST_DATE_KEY INT = 20180131

--CONVERT(INT, CONCAT(YEAR(EOMONTH ( CONVERT(VARCHAR(50),@DATE_KEY) , -1)), 
					--CAST(MONTH(EOMONTH (CONVERT(VARCHAR(50), @DATE_KEY) , -1)) AS VARCHAR(2)),DAY(EOMONTH (CONVERT(VARCHAR(50), @DATE_KEY ), -1))));  

select @date_key as date_key, @LAST_DATE_KEY AS LAST_MONTH, @afs_prod_dt as AFS_PROD_DT, @OSI_PROD_DT AS OSI_PROD_DT, @RDM_PROD_dT AS RDM_PROD_DT;

SELECT * INTO #STATUS 
FROM SB_PA_MARGARET.[FRB\mlan].[TBL_CHECK_STATUS]
WHERE [CURRENT] = 'Y' AND [DATE_KEY] = @LAST_DATE_KEY; --APPEND LAST MONTH CHECK STATUS

SELECT EOM.DATE_KEY
	  ,EOM.SRC_TYPE_CD
	  ,EOM.Acct_Nbr
	  ,EOM.Bisys_Nbr_Fmt
	  ,EOM.[TRANCHE_ACCT_NBR]
	  ,EOM.[BALANCE_SHEET_CATEGORY_CA]
	  ,EOM.[GL_DESCRIPTION_CA]
	  --,EOM.ORIG_BALANCE
	  ,EOM.[COMMITMENT]
	  ,EOM.[NET_BOOK_BAL]
	  ,EOM.[ACCT_OPEN_DT]
	  ,CASE 
		   WHEN WB.[LTV_ORIG] IS NOT NULL THEN WB.[LTV_ORIG] 
		   WHEN IP.[LTV_Final] IS NOT NULL THEN IP.[LTV_Final]
		   ELSE CASE WHEN PLF.[LienPosition]=1 THEN IIF(EMP.ELTV IS NULL, PLF.ELTV, EMP.ELTV)
				     WHEN PLF.[LienPosition]<>1 THEN IIF(EMP.ECLTV IS NULL, PLF.ECLTV, EMP.ECLTV)
					 END
	   END AS LTV_ORIG
	  ,EOM.[LIEN_POSITION] as [LIEN_POSITION]
	  ,CASE WHEN IP.[LTV_Final] IS NOT NULL THEN 'IP DATASET' -- UPDATE CHECK STATUS FOR IP DATA
			ELSE #STATUS.[CHECK_STATUS] END AS [CHECK_STATUS]   	        
      ,CASE WHEN #STATUS.ACCT_NBR IS NOT NULL THEN 'Y' ELSE 'N' END AS [INCLUDED]
	  ,CASE WHEN EOM.SRC_TYPE_CD = 'AFS' THEN
			CASE WHEN (EOM.[SRC_PROD_CD] IN ('132021',		'132025', 	'132052',
									'132053',		'132028',		'132045','132051',
									'132029',	'132062',	'132063', '132069', '132056',
									'132057', '132059', '132061',	'132036',
									'132088') Or CAST(EOM.[SRC_PROD_CD] AS INT) >132111) THEN 'Y' 
				 WHEN EOM.[SRC_PROD_CD] = '132048' AND (EOM.LOAN_COLLAT_TYPE >= 483  AND EOM.LOAN_COLLAT_TYPE<600) THEN 'Y'
			     ELSE 'N' END
			WHEN EOM.SRC_TYPE_CD IN ( 'ML', 'IL') THEN
				CASE WHEN [BALANCE_SHEET_CATEGORY_CA] = 'Unsecured Loans/Lines of Credit' THEN 'N'
				ELSE 'Y' END
		ELSE 'N'
		END AS 'LTV_REQUIRED_FLAG'
  
  INTO #ALL

  FROM [CreditAdmin].[dbo].[CA_GL_RECONCILED_MAKE_TABLE_CURR] EOM

  LEFT JOIN [PLProd].[dbo].[vw_powerlender] PL
	ON PL.A304_CustomerKey =
		CASE 
		WHEN SUBSTRING(EOM.Bisys_Nbr_Fmt,4,1)='7'
			 THEN '0' + SUBSTRING(EOM.Bisys_Nbr_Fmt,4,6) + RIGHT(EOM.Bisys_Nbr_Fmt,1)
		ELSE 
			 RIGHT(EOM.Bisys_Nbr_Fmt,8)
		END 
  LEFT JOIN [PLProd].[dbo].[vw_LoanFacts] PLF
	ON PLF.Loan_Key =
		CASE 
		WHEN SUBSTRING(EOM.Bisys_Nbr_Fmt,4,1)='7'
			 THEN LEFT(EOM.Bisys_Nbr_Fmt,2) + '-0' + SUBSTRING(EOM.Bisys_Nbr_Fmt,4,6) + RIGHT(EOM.Bisys_Nbr_Fmt,1)
		ELSE 
			 EOM.Bisys_Nbr_Fmt
		END
  LEFT JOIN [PLProd_EMPLOYEE].[dbo].[VW_LOAN_FACT_EMP_CUSO] EMP
	ON EMP.[Customer_key] =
		CASE 
		WHEN SUBSTRING(EOM.Bisys_Nbr_Fmt,4,1)='7'
			 THEN '0' + SUBSTRING(EOM.Bisys_Nbr_Fmt,4,6) + RIGHT(EOM.Bisys_Nbr_Fmt,1)
		ELSE 
			 RIGHT(EOM.Bisys_Nbr_Fmt,8)
		END
  LEFT JOIN [CREMF].[dbo].[CRE_Collateral] IP
    ON right(EOM.Bisys_Nbr_Fmt,8)=IP.[BisysNo_Short] 
  
  LEFT JOIN #STATUS ON #STATUS.ACCT_NBR = EOM.[ACCT_NBR]

  LEFT JOIN [SB_PA_Margaret].[FRB\mlan].[TBL_LTV_EOM] WB ON WB.ACCT_NBR = EOM.ACCT_NBR AND WB.DATE_KEY = 20180131

  Where EOM.Date_Key=@DATE_KEY AND EOM.SRC_TYPE_CD in ('AFS','ML','IL') --AND Status_Description='OPEN'
  ORDER BY SRC_TYPE_CD, [BALANCE_SHEET_CATEGORY_CA]--, #STATUS.[LTV_ORIG]*100 DESC
  ;

  --UPDATE A
  --SET --A.[INCLUDED] = CASE WHEN #STATUS.ACCT_NBR IS NOT NULL THEN 'Y' ELSE 'N' END,
		----A.CHECK_STATUS = CASE WHEN #STATUS.ACCT_NBR IS NOT NULL THEN #STATUS.STATUS ELSE 'NA' END ,
		--A.ORIG_LTV = IIF(A.ORIG_LTV IS NULL, #STATUS.ORIG_LTV , A.ORIG_LTV),
		--A.ORIG_FICO = IIF(A.ORIG_FICO IS NULL, #STATUS.[Original FICO] , A.ORIG_FICO),
		--A.FICO_CURR = IIF(A.FICO_CURR IS NULL, #STATUS.[Current FICO] , A.FICO_CURR) 
  --FROM #ALL A  
  --LEFT JOIN #STATUS ON #STATUS.ACCT_NBR = EOM.[ACCT_NBR]
  --;

 ----================UPDATE ORIGINAL LTV FROM EAGLEVISION RESOURCES=====================
 WITH ORIG_LTV_OSI AS (
 
 --SELECT MAX(PROD_DT) FROM EAGLEVISION.DBO.T_LDW_MLNS
 SELECT CONVERT(VARCHAR(20),ACCT_NBR) AS ACCT_NBR, ORIG_LTV_RATIO AS ORIG_LTV
 FROM EAGLEVISION.DBO.T_LDW_MLNS
 WHERE PROD_DT = '2018-02-28' AND ORIG_LTV_RATIO IS NOT NULL

 UNION 

 SELECT CONVERT(VARCHAR(20),ACCT_NBR) AS ACCT_NBR, [NUM_VALUE_AMT] AS ORIG_LTV
 FROM [EagleVision].[dbo].[V_TVN_IL_USER_DEF_MSTR_REC_CURR] ILNS 
 WHERE [MSTR_REC_NBR] = 737 AND [NUM_VALUE_AMT] IS NOT NULL
 )

  UPDATE A
  SET A.LTV_ORIG = ORIG_LTV_OSI.ORIG_LTV
  FROM #ALL A
  INNER JOIN ORIG_LTV_OSI ON ORIG_LTV_OSI.ACCT_NBR = A.ACCT_NBR
  WHERE A.LTV_ORIG IS NULL AND ORIG_LTV_OSI.ORIG_LTV IS NOT NULL;

--===============UPDATE DECIMAL FORMAT LTV=============================================
  
  UPDATE A
  SET A.LTV_ORIG = A.LTV_ORIG *100
  --SELECT ACCT_NBR, LTV_ORIG
  FROM #ALL A
  WHERE A.LTV_ORIG <1.000000;

--===============UPDATE VALUE 0 LTV=============================================  
  UPDATE A
  SET A.LTV_ORIG = NULL
  --SELECT ACCT_NBR, LTV_ORIG
  FROM #ALL A
  WHERE A.LTV_ORIG = 0 ;

--===============UPDATE ON --TEMP-- FILE=============================================  
	--UPDATE A
	--SET A.CHECK_STATUS = ST.CHECK_STATUS, A.LTV_ORIG = ST.LTV_ORIG
	--FROM #ALL A
	--INNER JOIN [SB_PA_Margaret].[dbo].[SCRUBBED_COMBINED_CURR] ST ON ST.ACCT_NBR = A.ACCT_NBR
	--WHERE ST.DATE_KEY = 20180228
	--;
 -- CHECK STATUS UPDATE HAS TO HAPPEN IN SAME QUERY ENVIRONMENT!!!.  NEED TO RUN IT IN SAME MAKE LTV TABLE FILE!!!

------========== CONSOLIDATE LTV FICO IN ONE TABLE FOR REVIEW==============
	--SELECT  DATE_KEY
	--  ,SRC_TYPE_CD
	--  ,Acct_Nbr
	--  ,Bisys_Nbr_Fmt
	--  --,FICO_CURR
	--  --,FICO_ORIG
	--  ,LTV_ORIG
	--  ,CHECK_STATUS
	--FROM #ALL
	--WHERE LTV_ORIG > 80

------======= OUTPUT LTV FICO IN WRITEBACK FORM=======
WITH WV AS (
SELECT 'LTV_ORIG' AS FIELD, ACCT_NBR, SRC_TYPE_CD, IIF(LTV_ORIG = 0, NULL, CONVERT(DECIMAL(16,4), (LTV_ORIG/100))) AS VALUE, 
	CONVERT(DATE, '2/28/2018') AS EFFECTIVE_FROM_DT, '' AS EFFECTIVE_TO_DT, 'Original LTV value Update' AS REASON, 'mlan' AS [USER_ID]
--FROM #ALL
FROM [SB_PA_Margaret].[FRB\mlan].[TBL_LTV_TEMP]
WHERE [BALANCE_SHEET_CATEGORY] IN ('Commercial Real Estate Mtgs', 'Home Equity Lines of Credit', 'Investor', 'Loans Held for Sale', 'MF / Comm''l Construction',
	'Multifamily Mtgs 5+ Units','REO - HELOC','SFR Construction Loans','Single Family Mtgs 1-4 Units')
)
----======= IMPORT LTV AND FICO IN WRITEBACK FILE INTO THE WB TABLE=======
INSERT INTO [SB_PA_Margaret].[FRB\mlan].[TBL_WB_EOM] (
       [FIELD]
      ,[ACCT_NBR]
      ,[SRC_TYPE_CD]
      ,[VALUE]
      ,[EFFECTIVE_FROM_DT]
      ,[EFFECTIVE_TO_DT]
      ,[REASON]
      ,[USER_ID]
      ,[INSERT_DT]
)
SELECT
       [FIELD]
      ,[ACCT_NBR]
      ,[SRC_TYPE_CD]
      ,[VALUE]
      ,[EFFECTIVE_FROM_DT]
      ,[EFFECTIVE_TO_DT]
      ,[REASON]
      ,[USER_ID]
      ,GETDATE() [INSERT_DT]
  FROM WV

----==================================NULL LTV CHECK==============================================================================

--WITH NULL_LTV AS (
--SELECT SRC_TYPE_CD
--	  ,Acct_Nbr
--	  ,Bisys_Nbr_Fmt
--	  ,[LIEN_POSITION]
--	  ,[BALANCE_SHEET_CATEGORY_CA]
--	  ,[GL_DESCRIPTION_CA]
--	  ,LTV_ORIG
--FROM #ALL
--WHERE LTV_ORIG IS NULL -- AND (BALANCE_SHEET_CATEGORY_CA like 'SF%' OR [GL_DESCRIPTION_CA] LIKE 'SF%' )
--		--AND BALANCE_SHEET_CATEGORY_CA <> 'Investor' 
--		--AND BALANCE_SHEET_CATEGORY_CA NOT LIKE '%CHARGEOFF%' 
--		--AND [GL_DESCRIPTION_CA] <> 'SFR Sold to Investor'
--				--AND  ( [GL_DESCRIPTION_CA] LIKE '%MF%' 
--				--OR BALANCE_SHEET_CATEGORY_CA like 'Commercial%')
--)

--SELECT NULL_LTV.ACCT_NBR,NULL_LTV.Bisys_Nbr_Fmt,NULL_LTV.[LIEN_POSITION],[BALANCE_SHEET_CATEGORY_CA],[GL_DESCRIPTION_CA],
--		LTV_ORIG,--PLF.ELTV,PLF.ECLTV,PLF.[LienPosition], 
--		MLNS.ORIG_LTV_RATIO, ILNS.[NUM_VALUE_AMT],IP.[LTV_Final]
--FROM NULL_LTV 
-- -- LEFT JOIN [PLProd].[dbo].[vw_LoanFacts] PLF
--	--ON PLF.Loan_Key =
--	--	CASE 
--	--	WHEN SUBSTRING(NULL_LTV.Bisys_Nbr_Fmt,4,1)='7'
--	--		 THEN LEFT(NULL_LTV.Bisys_Nbr_Fmt,2) + '-0' + SUBSTRING(NULL_LTV.Bisys_Nbr_Fmt,4,6) + RIGHT(NULL_LTV.Bisys_Nbr_Fmt,1)
--	--	ELSE 
--	--		 NULL_LTV.Bisys_Nbr_Fmt
--	--	END
--   LEFT JOIN [CREMF].[dbo].[CRE_Collateral] IP ON right(NULL_LTV.Bisys_Nbr_Fmt,8)=IP.[BisysNo_Short] 
--   LEFT JOIN EAGLEVISION.DBO.T_LDW_MLNS MLNS ON CONVERT(VARCHAR(20),MLNS.ACCT_NBR) = NULL_LTV.ACCT_NBR AND MLNS.PROD_DT = '2018-01-31'
--   --LEFT JOIN [EagleVision].[dbo].[V_LDW_ILNS_CURR] ILNS ON CONVERT(VARCHAR(20),ILNS.ACCT_NBR) = NULL_LTV.ACCT_NBR
--   LEFT JOIN [EagleVision].[dbo].[V_TVN_IL_USER_DEF_MSTR_REC_CURR] ILNS ON CONVERT(VARCHAR(20),ILNS.ACCT_NBR) = NULL_LTV.ACCT_NBR AND ILNS.[MSTR_REC_NBR] = 737
--	  --,EOM.ORIG_BALANCE

----====================LTV CHECK AFTER UPDATE========================================
-- --SELECT * FROM #ALL WHERE ACCT_NBR = '225449293'
--  DECLARE @LAST_DATE_KEY INT = 20180131
--  SELECT #ALL.*--, #STATUS.[LTV_ORIG] AS OLD_LTV_ORIG 
--  FROM #ALL 
-- -- LEFT JOIN #STATUS 
--	--ON #STATUS.ACCT_NBR = #ALL.[ACCT_NBR]
--  WHERE ( #ALL.LTV_ORIG >80 OR #ALL.LTV_ORIG IS NULL) 
--  AND ([CHECK_STATUS] IS NULL OR LEN([CHECK_STATUS]) <1) AND #ALL.LTV_REQUIRED_FLAG = 'Y'
--  AND ([ACCT_OPEN_DT] > EOMONTH(CONVERT(DATE, CONVERT(VARCHAR,@LAST_DATE_KEY))) OR INCLUDED = 'Y')
--  AND [BALANCE_SHEET_CATEGORY_CA] <> 'Unsecured Loans/Lines of Credit'
--  ORDER BY #ALL.LTV_ORIG DESC


  --SELECT TOP 20 * FROM #ALL
  --WHERE SRC_TYPE_CD = 'IL'  AND ([CHECK_STATUS] IS NULL OR LEN([CHECK_STATUS]) <1)
  --ORDER BY [NET_BOOK_BAL] DESC

  --SELECT TOP 20 * FROM #ALL
  --WHERE SRC_TYPE_CD = 'IL' AND ([CHECK_STATUS] IS NULL OR LEN([CHECK_STATUS]) <1)
  --ORDER BY [COMMITMENT] DESC

  --SELECT TOP 20 * FROM #ALL
  --WHERE SRC_TYPE_CD = 'ML' AND ([CHECK_STATUS] IS NULL OR LEN([CHECK_STATUS]) <1)
  --ORDER BY [NET_BOOK_BAL] DESC


--/**
--**/

--SELECT * FROM #ALL
--WHERE [BALANCE_SHEET_CATEGORY_CA] IS NULL


/****** APPEND NEW LOAN TO LTV TEMP TABLE  ******/

--INSERT INTO [SB_PA_Margaret].[FRB\mlan].[TBL_LTV_TEMP]
--(
--       [DATE_KEY]
--      ,[ACCT_OPEN_DT]
--      ,[LN_KEY]
--      ,[ACCT_NBR]
--      ,[TRANCHE_ACCT_NBR]
--      ,[BISYS_NBR_FMT]
--      ,[SRC_TYPE_CD]
--      ,[BALANCE_SHEET_CATEGORY]
--      ,[GL_DESCRIPTION]
--      ,[LTV_ORIG]
--      --,[FICO_ORIG]
--      --,[FICO_CURR]
--      ,[SCRUBBED_DATE]
--      ,[SCRUBBED_BY]
--      ,[EFFECTIVE_FROM_DT]
--      ,[CHECK_STATUS]
--)

--SELECT 
--       #all.[DATE_KEY]
--      ,#all.[ACCT_OPEN_DT]
--      ,EOM.[LN_KEY]
--      ,#ALL.[ACCT_NBR]
--      ,#ALL.[TRANCHE_ACCT_NBR]
--      ,#ALL.[BISYS_NBR_FMT]
--      ,#ALL.[SRC_TYPE_CD]
--      ,#ALL.[BALANCE_SHEET_CATEGORY_CA]
--      ,#ALL.[GL_DESCRIPTION_CA]
--      ,#ALL.[LTV_ORIG]
--      --,#ALL.[FICO_ORIG]
--      --,#ALL.[FICO_CURR]
--      ,GETDATE() AS [SCRUBBED_DATE]
--      ,'mlan' AS [SCRUBBED_BY]
--      ,CONVERT(DATE, CONVERT(VARCHAR(40), #ALL.DATE_KEY)) AS [EFFECTIVE_FROM_DT]
--      ,#ALL.[CHECK_STATUS]
--  FROM #ALL
--  LEFT JOIN RDM_LOAN.[ADJ].[T_FACT_LOAN_EOM] EOM
--	on EOM.ACCT_NBR = #ALL.ACCT_NBR and EOM.DATE_KEY = 20180228


/******========== APPEND NEW LOAN TO LTV EOM TABLE  AFTER WB******/
--DELETE FROM  [SB_PA_Margaret].[FRB\mlan].[TBL_LTV_EOM] WHERE DATE_KEY = 20180228 

--INSERT INTO [SB_PA_Margaret].[FRB\mlan].[TBL_LTV_EOM]
--(
--       [DATE_KEY]
--      ,[ACCT_OPEN_DT]
--      ,[LN_KEY]
--      ,[ACCT_NBR]
--      ,[TRANCHE_ACCT_NBR]
--      ,[BISYS_NBR_FMT]
--      ,[SRC_TYPE_CD]
--      ,[BALANCE_SHEET_CATEGORY]
--      ,[GL_DESCRIPTION]
--      ,[LTV_ORIG]
--      --,[FICO_ORIG]
--      --,[FICO_CURR]
--      ,[SCRUBBED_DATE]
--      ,[SCRUBBED_BY]
--      ,[EFFECTIVE_FROM_DT]
--      ,[CHECK_STATUS]
--)

--SELECT  
--      [DATE_KEY]
--      ,[ACCT_OPEN_DT]
--      ,[LN_KEY]
--      ,[ACCT_NBR]
--      ,[TRANCHE_ACCT_NBR]
--      ,[BISYS_NBR_FMT]
--      ,[SRC_TYPE_CD]
--      ,[BALANCE_SHEET_CATEGORY]
--      ,[GL_DESCRIPTION]
--      ,[LTV_ORIG]
--      ,[SCRUBBED_DATE]
--      ,[SCRUBBED_BY]
--      ,[EFFECTIVE_FROM_DT]
--      ,[CHECK_STATUS]
--  FROM [SB_PA_Margaret].[FRB\mlan].[TBL_LTV_TEMP]
--  WHERE DATE_KEY = 20180228 


--SELECT * FROM   [SB_PA_Margaret].[FRB\mlan].[TBL_FICO_TEMP]
--WHERE ACCT_NBR IN (
--'0210028770-0059',
--'0210249376-0026',
--'0210255613-0034',
--'0210749763-0018',
--'120711481',
--'124621595',
--'125980081',
--'125986476',
--'127059272',
--'127067242',
--'127068117',
--'127076946',
--'220752782',
--'225671961',
--'227063688',
--'227072184',
--'227073125'
--)
----AND DATE_KEY = 20180131
--ORDER BY ACCT_NBR




